DROP TABLE `cardie_visite_ef`;
CREATE TABLE IF NOT EXISTS `cardie_visite_ef` (
  `ID_EF` int(11) NOT NULL AUTO_INCREMENT,
  `FK_ID_VISITE` int(11) NOT NULL,
  `FK_ID_PERS_RESS` int(11) NOT NULL,
  `ETAT` int(2) NOT NULL DEFAULT '0',
  `REMARQUES` tinytext NOT NULL,
  PRIMARY KEY (`ID_EF`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=42 ;
